#![allow(dead_code)]

#[derive(Debug)]
// renamed version of ItemInfo cuz i dont want to share it :P
pub struct ItemInfo {
    pub overlay_object: u64,

    pub id: u16,
    pub unk_0u32: u32,
    pub unk_1u32: u32,
    pub unk_2u32: u32,
    pub unk_3u32: u32,
    pub tree_time: u32,
    pub heal_time: u32,
    pub seed_color: u32,
    pub unk_4u32: u32,
    pub unk_5u32: u32,
    pub texture_hash: u32,
    pub unk_6u32: u32,
    pub unk_7u32: u32,
    pub extra_file_hash: u32,
    pub seed_overlay_color: u32,

    pub flags: u16,
    pub rarity: u16,

    pub posx: u8,
    pub posy: u8,
    pub layer: u8,
    pub storage: u8,
    pub material: u8,
    pub bodypart: u8,
    pub maxcount: u8,
    pub seed_base: u8,
    pub collision: u8,
    pub item_type: u8,
    pub tree_base: u8,
    pub tree_leaves: u8,
    pub seed_overlay: u8,
    pub visual_effect: u8,
    pub hits_to_destroy: u8,

    pub name: String,
    pub ia: String,
    pub bname: String,
    pub aa: String,
    pub texture_path: String,
    pub estr: String,
    pub bprefix: String,
    pub bsuffix: String,
    pub babil: String,
    pub extra_file_path: String,
    pub pinfo: String,

    pub ams: u32,
    pub lid: u32,
    pub wid: u32,

    pub unk0: [u8; 4],
    pub unk1: [u8; 60],
    pub bps: [u8; 9],

    pub extra: bool,
}

impl Default for ItemInfo {
    fn default() -> Self {
        Self {
            overlay_object: Default::default(),
            id: Default::default(),
            unk_0u32: Default::default(),
            unk_1u32: Default::default(),
            unk_2u32: Default::default(),
            unk_3u32: Default::default(),
            tree_time: Default::default(),
            heal_time: Default::default(),
            seed_color: Default::default(),
            unk_4u32: Default::default(),
            unk_5u32: Default::default(),
            texture_hash: Default::default(),
            unk_6u32: Default::default(),
            unk_7u32: Default::default(),
            extra_file_hash: Default::default(),
            seed_overlay_color: Default::default(),
            flags: Default::default(),
            rarity: Default::default(),
            posx: Default::default(),
            posy: Default::default(),
            layer: Default::default(),
            storage: Default::default(),
            material: Default::default(),
            bodypart: Default::default(),
            maxcount: Default::default(),
            seed_base: Default::default(),
            collision: Default::default(),
            item_type: Default::default(),
            tree_base: Default::default(),
            tree_leaves: Default::default(),
            seed_overlay: Default::default(),
            visual_effect: Default::default(),
            hits_to_destroy: Default::default(),
            name: Default::default(),
            ia: Default::default(),
            bname: Default::default(),
            aa: Default::default(),
            texture_path: Default::default(),
            estr: Default::default(),
            bprefix: Default::default(),
            bsuffix: Default::default(),
            babil: Default::default(),
            extra_file_path: Default::default(),
            pinfo: Default::default(),
            ams: Default::default(),
            lid: Default::default(),
            wid: Default::default(),
            unk0: [0u8; 4],
            unk1: [0u8; 60],
            bps: [0u8; 9],
            extra: Default::default(),
        }
    }
}
